### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by AnthyG** [AnthyG/ThunderNote#1]
### Main Points
- [ ] Private notes
- [ ] Note-Sharing
- [ ] Options
- [ ] Markdown-Support

-------

#### Private notes
- [ ] Auto-encrypt (Encrypts with users public-key using ECIES)
- [ ] Manual-encrypt (Encrypts with custom AES-Inputs)

#### Note-Sharing
- ?!read-only?!
- to:
- - cert-user-name/ public-key (encrypt with other users public-key using ECIES)
- - All (Will be encrypted with users own public-key, using AES, so other users can decrypt with the owners public-key)

#### Options
- [ ] Auto-save (refers to _Private Notes > Auto-encrypt_)
- [ ] Night-mode

#### Markdown-Support
Quite obvious what it does,.. right!?

#### ?other name?
- Notez
- zNote
- ZNote
- 0Note
- ZeroNote
